### ISSUE TITLE
Django 1.11 `RadioFieldRender` removed

### ISSUE THREAD

**Issue by lukaszbanasiak** [cypreess/django-getpaid#114]
Some undocumented classes in `django.forms.widgets` are removed in Django 1.11.

Ref: https://docs.djangoproject.com/en/1.11/releases/1.11/#template-widget-incompatibilities-1-11

```
  File "/getpaid/forms.py", line 6, in <module>
    from django.forms.widgets import HiddenInput, RadioSelect, RadioFieldRenderer, RadioChoiceInput
ImportError: cannot import name 'RadioFieldRenderer'
```

**Comment by lukaszbanasiak** [comment]
Solved by https://github.com/cypreess/django-getpaid/issues/115

**Comment by ludwiktrammer** [comment]
It seems the version with this fix is still not on PyPi. Are there any plans for releasing a new stable version?
